[package]
name = "incodoc-ssg"
version = "0.1.0"
edition = "2024"
authors = ["Cody Bloemhard <codybloemhard@gmail.com>"]
readme = "README.md"
license = "GPL-3.0-only"
repository = "https://github.com/codybloemhard/incodoc-ssg"
description = "Static site generator using incodoc."
categories = ["command-line-utilities"]

[dependencies]
# incodoc-to-html = "0.1.0"
incodoc-to-html = { path = "../incodoc-to-html" }
md-to-incodoc = "0.3.0"
zen-colour = "1.1.2"
clap = { version = "4.5.59", features = ["derive"] }
simpleio = "0.2.3"
incodoc = "0.6.1"

