[package]
name = "incodoc-ssg"
version = "0.1.0"
edition = "2024"
authors = ["Cody Bloemhard <codybloemhard@gmail.com>"]
readme = "README.md"
license = "GPL-3.0-only"
repository = "https://github.com/codybloemhard/incodoc-ssg"
description = "Static site generator using incodoc."
categories = ["command-line-utilities"]

[dependencies]
incodoc = "0.6.2"
# incodoc = { path = "../incodoc" }
# incodoc-to-html = "0.1.0"
incodoc-to-html = { path = "../incodoc-to-html" }
md-to-incodoc = "0.3.1"
# md-to-incodoc = { path = "../md-to-incodoc" }
zen-colour = "1.1.2"
simpleio = "0.2.3"
clap = { version = "4.5.59", features = ["derive"] }

